#!/bin/bash

sed -i 's/ffft\///g' fftreal/*

rename 's/vi/q/' headers/*
sed -i 's/vi/q/g' headers/*
sed -i 's/VI/Q/g' headers/*
sed -i 's/Vi/Q/g' headers/*
sed -i 's/qrtual/virtual/g' headers/*

rename 's/vi/q/' sources/*
sed -i 's/vi/q/' sources/*
sed -i 's/VI/Q/' sources/*
sed -i 's/Vi/Q/' sources/*
sed -i 's/qrtual/virtual/g' sources/*
