#############################################################################################
# Parameters
#############################################################################################
SET(PACKAGE_ARCHITECTURE "i386")
IF(${ARCHITECTURE} MATCHES "64bit")
	SET(PACKAGE_ARCHITECTURE "amd64")
ENDIF()

IF(${DISTRO} MATCHES "Debian")
	SET(CPACK_GENERATOR "DEB;")
ELSEIF(${DISTRO} MATCHES "Redhat")
	SET(CPACK_GENERATOR "RPM;")
ENDIF()

IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
	SET(CPACK_GENERATOR "${CPACK_GENERATOR}STGZ")
ENDIF()
#############################################################################################


#############################################################################################
# Basic package information
#############################################################################################
set(CPACK_SET_DESTDIR TRUE)
set(CPACK_INSTALL_PREFIX ${INSTALL_LOCATION})
SET(CPACK_PACKAGING_INSTALL_PREFIX ${INSTALL_LOCATION})
SET(CPACK_PACKAGE_DEFAULT_LOCATION ${INSTALL_LOCATION})
SET(CPACK_PACKAGE_DESCRIPTION_FILE ${README_FILE})
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${SHORT_DESCRIPTION})
SET(CPACK_PACKAGE_FILE_NAME "${PACKAGE}-${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}-${PACKAGE_ARCHITECTURE}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY ${INSTALL_LOCATION})
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${NAME}-${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
SET(CPACK_PACKAGE_NAME ${NAME})
SET(CPACK_PACKAGE_VENDOR ${NAME})
SET(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})
SET(CPACK_PACKAGE_VERSION "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "${PACKAGE}-${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}")
SET(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}-${PACKAGE_ARCHITECTURE}")
SET(CPACK_RESOURCE_FILE_LICENSE ${LICENSE_FILE})
SET(CPACK_RESOURCE_FILE_README ${README_FILE})
#############################################################################################


#############################################################################################
# Specific package information
#############################################################################################
IF(${DISTRO} MATCHES "Debian")
	SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "${MAINTAINER} <${EMAIL}>")
	SET(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${PACKAGE_ARCHITECTURE})
	SET(CPACK_DEBIAN_PACKAGE_SECTION libs)
	SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION_SUMMARY ${SHORT_DESCRIPTION})
	SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "${SHORT_DESCRIPTION}
 ${LONG_DESCRIPTION}
Homepage: ${HOMEPAGE}")
	SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt${QT_VERSION_MAJOR}-core (>= ${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}.${QT_VERSION_PATCH})")
ELSEIF(${DISTRO} MATCHES "Redhat")
	SET(CPACK_RPM_PACKAGE_PROVIDES "libqrealfourier.so")
	SET(CPACK_RPM_PACKAGE_SUMMARY ${SHORT_DESCRIPTION})
	SET(CPACK_RPM_PACKAGE_ARCHITECTURE ${PACKAGE_ARCHITECTURE})
	SET(CPACK_RPM_PACKAGE_LICENSE ${LICENSE})
	SET(CPACK_RPM_PACKAGE_GROUP "Development/Libraries")
	SET(CPACK_RPM_PACKAGE_DESCRIPTION "${SHORT_DESCRIPTION}
	${LONG_DESCRIPTION}")
	set(CPACK_RPM_PACKAGE_REQUIRES "libqt{QT_VERSION_MAJOR}-core >= ${QT_VERSION_MAJOR}.${QT_VERSION_MINOR}.${QT_VERSION_PATCH}")
ENDIF()
#############################################################################################


INCLUDE(CPack)
