SET(NAME "QRealFourier")
SET(PACKAGE "qrealfourier")
SET(VERSION_MAJOR "0")
SET(VERSION_MINOR "3")
SET(VERSION_PATCH "0")
SET(SHORT_DESCRIPTION "Qt Fast Fourier Transform")
SET(LONG_DESCRIPTION "A Qt-based library for Fast Fourier Transforms (FFTs).")
SET(MAINTAINER "Christoph Stallmann")
SET(EMAIL "qrealfourier@visore.org")
SET(HOMEPAGE "http://www.visore.org")
SET(INSTALL_LOCATION "/usr")
SET(LICENSE "LGPLv3.0")
SET(COPYRIGHT "Copyright (c) 2013 Christoph Stallmann, University of Pretoria")
SET(README_FILE ${CMAKE_CURRENT_SOURCE_DIR}/../ReadMe.txt)
SET(LICENSE_FILE ${CMAKE_CURRENT_SOURCE_DIR}/../License.txt)
